#!/usr/bin/env perl
package EchoBot;
use v5.10;
use Bot::Backbone;

service chat_bot => (
    service    => 'ConsoleChat',
    name       => 'echo',
);

service group_foo => (
    service    => 'GroupChat',
    chat       => 'chat_bot',
    group      => 'foo',
    dispatcher => 'default',
);

# service instant_message => (
#     service    => 'DirectChat',
#     chat       => 'chat_bot',
#     dispatcher => 'default',
# );

dispatcher default => as {
    command '!echo' => given_parameters { 
        parameter echo_this => ( match => qr/.+/ );
    } respond {
        my $message = shift;
        $message->parameters->{echo_this};
    };
};

my $bot = EchoBot->new;
$bot->run;
