#!/usr/bin/env perl
package EchoBot;
use v5.10;
use Bot::Backbone;

my $debug = 0;

if ($debug == 1) {
    service chat_bot => (
        service      => 'ConsoleChat',
        bot_username => 'echo',
        bot_nickname => 'echo',
    );
}
else {
    service chat_bot => (
        service  => 'JabberChat',
        username => 'echo',
        domain   => 'example.com',
        resource => 'echobot',
        password => 'secret',
        host     => 'talk.google.com',
        connection_args => {
            disable_iq_auth => 1,
        },
    );
}

service group_foo => (
    service    => 'GroupChat',
    chat       => 'chat_bot',
    group      => 'foo',
    dispatcher => 'default',
);

service instant_message => (
    service    => 'DirectChat',
    chat       => 'chat_bot',
    dispatcher => 'default',
);

dispatcher default => as {
    command '!echo' => given_parameters { 
        parameter echo_this => ( match => qr/.+/ );
    } respond {
        my $message = shift;
        $message->parameters->{echo_this};
    };
};

my $bot = EchoBot->new;
$bot->run;
