#!/usr/bin/env perl
package TickBot;
use v5.10;
use Bot::Backbone;

use POE;

my $debug = 0;

if ($debug == 1) {
    service chat_bot => (
        service      => 'ConsoleChat',
        bot_username => 'tick',
        bot_nickname => 'tock',
    );
}
else {
    service chat_bot => (
        service  => 'JabberChat',
        username => 'tick',
        domain   => 'example.com',
        resource => 'ticktock',
        password => 'secret',
        host     => 'secret',
    );
}

service group_foo => (
    service     => 'GroupChat',
    chat        => 'chat_bot',
    group       => 'foo',
);

my $bot = TickBot->new;

POE::Session->create(
    inline_states => {
        _start => sub {
            $_[KERNEL]->delay(tick => 1);
        },
        tick => sub {
            if (defined $bot->services->{group_foo}) {
                $bot->services->{group_foo}->send_message(text => 'tick');
                $_[KERNEL]->delay(tock => 1);
            }
        },
        tock => sub {
            if (defined $bot->services->{group_foo}) {
                $bot->services->{group_foo}->send_message(text => 'tock');
                $_[KERNEL]->delay(tick => 1);
            }
        },
    },
);

$bot->run;
